### ISSUE TITLE
Enhance collaboration capabilities of `ideas`

### ISSUE THREAD

**Issue by janejuenyang** [growthbook/growthbook#434]
Documentation is one of GrowthBook's strengths: there are many places you can include context and discussions around a feature, experiment, or idea. However right now these features don't allow teams to readily collaborate on developing ideas because there's a lack of notifications or ability to tag teammates on comments. These missing features disincentivize using GrowthBook as the place to really discuss ideas, which is unfortunate since it would be great to keep the ideas, any subsequent experiment data, and related conversation all together in one place.

What I'd love to see added to GrowthBook on a collaboration front include:

- [ ] configurable notifications similar to GitHub's, where you can choose to get notified in-app and/or via email on everything related to a specific experiment/feature/idea, just when you're mentioned, or literally everything
- [ ] letting you tag/mention teammates in comments, which sends a notification
- [ ] a way to export discussions, etc. so that you have the ability to take your data with you for whatever reason

**Comment by alyssamichelle** [comment]
Triage from the open-issues audit:

**Suggested action:** Fold into a GitHub Discussion

**Why:** Whether Ideas stays a product surface. This is a product-direction ask. Please convert or fold into a Discussion rather than keeping it as a standalone issue.

- [Event webhooks](https://docs.growthbook.io/app/webhooks/event-webhooks)
- [Permissions](https://docs.growthbook.io/account/user-permissions)

**Comment by alyssamichelle** [comment]
Advised to close after review: this is now being discussed in https://github.com/growthbook/growthbook/discussions/6822 (When should GrowthBook notify you?).
